# blender_manifest.toml
schema_version = "1.0.0"

id = "megu_accessory_check"
version = "1.0.0"
name = "Megu Shinonome Accessory Checker"
tagline = "Displays checks for Megu Shinonome submission in a UI panel"
type = "add-on"
maintainer = "Hideki Saito <hidekis@gmail.com>"

# Blender versions this add-on supports
blender_version_min = "4.20.0"

# License must be SPDX identifier
license = "SPDX:GPL-3.0-or-later"

# Optional: links for users
website = "https://hidekisaito.com"
documentation = "https://github.com/hsaito/blender_megu_check/blob/master/README.md"
tracker = "https://github.com/hsaito/blender_megu_check/issues"

# Tags help with discoverability
tags = ["Workflow", "Productivity", "Megu Shinonome", "Validation"]